export const models = [
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    chef: "Google",
    chefSlug: "google",
    providers: ["google"],
    toolSupport: true,
  },
  {
    id: "gemini-2.5-flash-lite",
    name: "Gemini 2.5 Flash Lite",
    chef: "Google",
    chefSlug: "google",
    toolSupport: true,
    providers: ["google"],
  },
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    chef: "Google",
    chefSlug: "google",
    providers: ["google"],
    toolSupport: true,
  },
  {
    id: "qwen/qwen3-32b",
    name: "Qwen 3",
    chef: "Qwen",
    chefSlug: "qwen",
    providers: ["groq"],
    toolSupport: true,
  },
  {
    id: "moonshotai/kimi-k2-instruct-0905",
    name: "Kimi K2",
    chef: "MoonshotAI",
    chefSlug: "moonshotai",
    providers: ["groq"],
    toolSupport: true,
  },
  {
    id: "openai/gpt-oss-20b",
    name: "GPT OSS 20B",
    chef: "OpenAI",
    chefSlug: "openai",
    providers: ["groq"],
    toolSupport: true,
  },
  {
    id: "openai/gpt-oss-120b",
    name: "GPT OSS 120B",
    chef: "OpenAI",
    chefSlug: "openai",
    providers: ["groq"],
    toolSupport: true,
  },
  {
    id: "openai/gpt-oss-safeguard-20b",
    name: "Safety GPT OSS 20B",
    chef: "OpenAI",
    chefSlug: "openai",
    providers: ["groq"],
  },
  {
    id: "meta-llama/llama-4-maverick-17b-128e-instruct",
    name: "Llama 4 Maverick",
    chef: "Meta",
    chefSlug: "meta",
    providers: ["groq"],
    toolSupport: true,
  },
  {
    id: "meta-llama/llama-4-scout-17b-16e-instruct",
    name: "Llama 4 Scout",
    chef: "Meta",
    chefSlug: "meta",
    providers: ["groq"],
    toolSupport: true,
  },
  {
    id: "deepseek-r1:1.5b",
    name: "Deepseek R1",
    chef: "Deepseek",
    chefSlug: "deepseek",
    providers: ["ollama"],
    toolSupport: false,
  },
];
